### ISSUE TITLE
Transaction filtered by an undefined payment_processor fails

### ISSUE THREAD

**Issue by krodyrobi** [PressLabs/silver#370] opened 2016-11-17 15:46 UTC
```
File "/home/krotz/workspace/silver/silver/api/views.py", line 894, in get_queryset
    if not payment_method.payment_processor.transaction_class:
AttributeError: 'unicode' object has no attribute 'transaction_class'
```

**Comment by bogdanpetrea** [comment] 2017-01-10 10:37
Next time please provide the steps to reproduce as well, because the code changes in time.

**Comment by bogdanpetrea** [comment] 2017-01-10 10:43
This was probably fixed with https://github.com/PressLabs/silver/pull/423, as in it works now. But the parameter name needs to be changed from payment_method to payment_processor, because it's named wrong in the TransactionFilter.

**Closed** 2017-01-10 10:49 UTC
Labels: bug, must
